name: Testing

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']

    env:
      OS: ubuntu-latest
      PYTHON: ${{ matrix.python-version }}

    steps:
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1.2.3
        with:
          exclude: "examples/example[3-4].wav"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install project and test tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[test]" pre-commit

      - name: Check with pre-commit
        run: SKIP=hadolint pre-commit run --all-files

      - name: Check classifier types
        run: mypy

      - name: Run tests and coverage
        run: pytest --cov-report=xml --random-order-seed=1

      - name: Upload coverage to Codecov
        if: matrix.python-version == '3.11'
        continue-on-error: true
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.BATBOT_CODECOV_TOKEN }}
          files: ./coverage/coverage.xml
          env_vars: OS,PYTHON
          fail_ci_if_error: true
